[package]
name = "hoshi"
version = "0.1.0"
authors = ["Brethland <ycy1207694344@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaze = "0.1"